project:
  type: website
  output-dir: docs

website:
  title: "Timea Balogh"
  site-url: http://tbalogh.github.io/"
  search: false
  description: "Timea Balogh is a PhD candidate at UC Davis."
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: interests.qmd
        text: Interests
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    page-footer: 
        center: "COPYRIGHT ©2024, TIMEA BALOGH. ALL RIGHTS RESERVED."
        background: light
      
format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

