project:
  type: website
  output-dir: docs
  resources:
  - ../CNAME

website:
  title: "Timea Balogh"
  site-url: http://tbalogh.github.io/"
  google-analytics: G-RWSEJBLGLN
  search: false
  description: "Timea Balogh is a PhD candidate at UC Davis."
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: https://www.dropbox.com/scl/fi/5cflbryd7n9xow9ippp3p/CV_Balogh_Timea.pdf?rlkey=etswxn0v9pjfhylbw4wdbucjy&st=t6jar61w&dl=0
        text: CV
  page-footer:
    background: light 
    left: Copyright 2025, Timea Balogh
    right: This website is made with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/tbalogh007/tbalogh.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

