---
page-layout: article
toc: true
section-divs: false
keep-md: false
format:
  html:
    anchor-sections: false
include-in-header:
  text: |
    <style type="text/css">
      h2, .h2 {
        border-bottom: none;
      }
    </style>
---

## Book

**"Who Attacks Whom? The Correlates of Media Reports of Inter-party Conflict and Cooperation Between European Elites." with James Adams, Josephine Andrews, Braeden Davis, Alexa Federice, Noam Gidron, and Will Horne.**

- Under review and contract with *Cambridge University Press*.

Abstract: Political elites’ inter-party conflict plausibly intensifies citizens’ hostility towards political opponents, i.e., affective polarization, while depressing their democratic satisfaction. Yet, while mass-level affective polarization and democratic satisfaction are widely studied, less is known about patterns of animosity among political elites. To address this gap, we analyze Western European politicians’ interparty interactions based on coded news reports in thirteen countries between 2001 and 2019, finding sharp cross-national and temporal variations in reported levels of interparty conflict. Within countries, elites’ interactions are more conflictual when parties diverge in their ideologies, their attitudes towards European integration, and their populist orientations, and are also related to governing coalition arrangements. Moderate economic downturns are associated with greater interparty conflict, but severe recessions – such as the global downturn beginning in 2009 – are associated with more interparty cooperation as elites work together to address the ongoing economic crisis. We also estimate that political elites’ interactions are far less conflictual in countries that feature more consensual political institutions, supporting Lijphart’s contention that consensualism promotes kinder, gentler, politics. Our findings illuminate how interparty cooperation and conflict vary within and between European party systems.

## Peer-Reviewed Publications

[**"Reproducibility and robustness of economics and political science research"**](https://doi.org/10.1038/s41586-026-10251-x) with Abel Brodeur et al. 2026. Published in *Nature*.

Abstract: Science aspires to be cumulative. Reproducibility efforts strengthen science by testing the reliability of published findings, promoting self-correction, and informing policy-making1. Computational reproductions, whereby independent researchers reproduce the results of published studies, are an essential diagnostic tool. Such efforts should have greater visibility. However, little social science reproduction and robustness has been conducted at scale. Here we reproduced original analyses and conducted robustness checks of 110 articles that were published in leading economics and political science journals with mandatory data and code sharing policies17,18. We found that more than 85% of published claims were computationally reproducible. In robustness checks, our reanalyses showed that 72% of statistically significant estimates remain significant and in the same direction, and the median reproduced effect size is nearly the same as the originally published effect size (that is, 99% of the published effect size). Additionally, 6 independent research teams examined 12 pre-specified hypotheses about determinants of robustness. Research teams with more experience found lower levels of robustness, and robustness did not correlate with author characteristics or data availability.

[**"Does Political Sophistication Moderate How Citizens Use Information to Infer Left-Right Distances between Parties?"**](https://www.tandfonline.com/doi/full/10.1080/17457289.2024.2429533?af=R) **with Will Horne, Simon Weschle, James Adams, and Christopher Wlezien. 2025. Published in the *Journal of Elections, Public Opinion and Parties*** .

Abstract: Research identifies numerous factors associated with citizens’ perceptions of party ideologies, including the Left-Right orientations of parties’ election manifestos, governing coalition arrangements, and media reports of party elites’ interactions. We analyze whether citizens’ reliance on these factors varies with their levels of education and political knowledge. In analyses of 51 election surveys from 18 countries between 2001 and 2015, we find that more politically sophisticated citizens attach (modestly) more weight to parties’ election manifestos and media reports of political elites’ interactions, but no evidence that sophistication moderates citizens’ reactions to governing coalition arrangements. There thus appears to be far more homogeneity than heterogeneity in the structure of party placement perceptions.

[**"A comment on Herzog, Baron, and Gibbons (2022)"**](https://www.econstor.eu/bitstream/10419/280748/1/I4R-DP097.pdf) **with Haley Daarstad and RyuGyung (Rio) Park. 2023. Published in *I4R Discussion Paper Series*, No. 97, Institute for Replication (I4R), s.l.**

Abstract: Herzog, Baron, and Gibbons (2022) explore the effects of exposure to official elite rhetoric and group cues on public support against the international nuclear weapons prohibition norm. The authors find that elite cues, in particular security and institutional cues, increase individuals' opposition to the Treaty on the Prohibition of Nuclear Weapons (TPNW). However, elite cues do not seem to have an effect on changing individuals' broader attitudes towards nuclear weapons, as measured by individuals' existing opposition to nuclear arms. We replicate and expand the authors' methods and results to test the robustness of the effects found in the study. First, we reproduce the main finding using the authors' original data and method. We do not find any coding errors that undermine the authors' analysis or conclusions. Second, we test the robustness of the results by (1) using a different operationalization of party identity, and (2) calculating additional subgroup analysis for gender. We find no significant differences between our replicated and the original results, however females' support for the TPNW is more responsive to security cues, while males' support is more responsive to institutions cues.

## Invitations to Revise and Resubmit

**"Conjoint Analysis of Interpersonal Affective Polarization: Limits of Partisan Bias in Dating, Housing, and Shopping" with Spencer Kiesel and Sharif Amlani.**

- Revise and Resubmit at *Political Science Quarterly*
- Presented at MPSA 2023, EPSA 2023, APSA 2023

Abstract: Scholarship shows that partisanship can inform individuals’ decisions in areas outside of politics, such as roommate choice, spousal selection, and economic behavior. However, few studies can systematically determine whether these decisions are based on partisanship or if they use partisanship to make inferences about other characteristics relevant to a given social choice. To determine to what extent partisanship informs decisions, we use a conjoint analysis to isolate the impact of partisanship on nonpolitical considerations across three types of social decisions: selecting a spouse to marry, a neighborhood to live in, and a business to frequent. We find that partisanship influences all three social decisions, even while controlling for other salient considerations. Further, we find that the degree to which partisanship matters is similar to and, in some cases, exceeds other relevant considerations. Overall, we show that when individuals make key decisions that affect the trajectory of their life, partisanship is a fundamental consideration.

## Working Papers

**"Policies, But for Whom? Testing the Effect of Social Group Appeals on British Voters’ Party Preferences" \[Job Market Paper\].**

- Presented at MPSA 2024, UC Davis Political Science Research Workshop Spring 2024, APSA 2024, NYU CESS Experimental Political Science Conference 2025, MPSA 2025, University of Strathclyde GPP Colloquium 2026
- Available upon request

Abstract: This study examines how political parties’ rhetorical appeals to social groups affect voters’ party preferences. Parties regularly appeal to social groups in their political communications, often pairing these appeals with policy promises. Yet, existing models of voting behavior focus almost exclusively on the role of policies. I use a pre-registered conjoint experiment fielded on a nationally representative sample of British adults that has voters consider parties’ promises to social groups in four different issue areas, and I show that voters punish parties who explicitly appeal to women, while appeals to workers are more generally accepted. Moreover these effects are moderated by the importance of the group to the individual. I find that the punishing effect of appeals to women are not driven by men, but rather those who do not consider women important. These findings shed light on the role of group attitudes in explaining voting behavior and advance our understanding of the consequences of group appeals.

**"The Greens' Disadvantage: How Party Reputations Shape Public Perceptions of Climate Policy" with RyuGyung (Rio) Park.**

- Under Review
- Presented at MPSA 2024, EPG 2024, APSA 2024, Graduate Students in International Political Economy (GSIPE) 2025 Conference
- Available upon request

Abstract: The environment-economy trade-off is regarded as one of the biggest obstacles to climate action. Ambitious decarbonization measures imply big economic costs, and electorates often worry about the economic repercussions of climate action. Do green parties suffer a systematic disadvantage from their reputation for too heavily prioritizing the environment over the economy? We theorize that, controlling for individuals’ ideology and policy issue priorities, climate policies supported by parties that have ex ante reputation for prioritizing the economy will be perceived more favorably than a green party, or a party with environmental issue competence. We use survey experiments in the U.S. and Germany to test our theory. Our results show that, while overall policy support remains relatively stable, having a green party as the main supporter of a policy creates more concerns for its economic consequences, which is consistent with our theory. While green parties appear to suffer a disadvantage, we do not find any evidence that right-wing parties experience an advantage.

**"The power of conversation: A survey experiment on AI-generated information and political behaviour" with Louise Luxton and Zoe Greene.**

- Presented at ECPR Joint Sessions 2026, COMPTEXT 2026, MPSA 2026, UCD Workshop on LLMs and Access to Political Information, EPSS 2026
- Upcoming presentations at APSA 2026

Abstract: Citizens increasingly seek political information from generative AI platforms such as ChatGPT. Despite concerns about the reliability of these platforms, extensive usage by citizens of these tools is poorly understood, including implications for political knowledge, voter behaviour, and political trust. Crucially, these platforms differ from news, social media, and search engines, in their interactivity and human-like tone. These unique characteristics may increase citizens' trust in the information provided and affect perceptions of political knowledge and efficacy. Yet, there is little causal research on the relationship between AI platforms and political behaviour. We examine the effects of AI-produced information on citizens’ political behaviour in the context of the European Parliament – characterised by low baseline knowledge and trust, high complexity, and weak partisanship. We field a preregistered survey experiment, with live participant interaction with a novel generative-AI transparency platform, varying two attributes: (1) interactivity (ability to ask follow-up questions) and (2) response tone (friendly, human-like vs. neutral), holding substantive content constant. We test whether AI’s unique conversationality increases citizen’s trust in the information provided,  AI generally, as well their political knowledge, efficacy, and institutional trust.

**"Representation Beyond Issues: How Parties Strategically Combine Group and Policy Appeals" with Louise Luxton.**

- Part of upcoming *Politics and Governance* Special Issue "Giving or Taking Voice: Representative Claims and Group Appeals in the Public Sphere" with Lucy Kinski and Clint Claessen
- Upcoming presentations at ECPR GC 2026

Abstract: A large body of extant research has examined how parties use both policy appeals and group appeals to increase electoral support among different groups in society. Yet, most of this work has occurred in parallel, and few scholars have investigated how parties strategically combine these two types of appeals – namely, what policies are promised to which groups and to what effect. This article advances this area of research by introducing a new dataset on parties’ policy and group appeals based on party manifesto data in Europe. We capture three key elements of group appeals: the group being appealed to, the policy promise being made (if any), and the specificity of the promise. We argue that whether groups receive symbolic gestures versus concrete policy commitments has profound implications for the quality and credibility of their representation. Using this data, we therefore test the extent to which different parties pair group appeals with substantive policy commitments and identify systematic patterns in how different policy areas become linked to particular groups. By distinguishing which groups receive symbolic versus substantive representation and in which policy domains, we bridge the emerging research on group appeals with foundational theories of representation. Our analysis also reveals under which circumstances certain groups are made politically absent through their omission from parties’ policy appeals.

**"Protecting Migrant Rights: Barriers to Naturalization" with Enrico Antonio La Viña and Jeannette Money.**

**"Introducing the Transnational Security Cooperation Agreement Dataset (TSCAD)" with Brandon Kinne.**

## Blog Posts and Reports

[**"From chatbots to the ballotbox – how voters used AI to learn about the Scottish Parliament election"**](https://www.electionanalysis.uk/scottish-election-analysis-2026/section-1-parties-and-the-campaign/from-chatbots-to-the-ballotbox-how-voters-used-ai-to-learn-about-the-scottish-parliament-election/) **with Louise Luxton, Elise Frelin, and Zoe Greene.**

[**"Auditing AI Chatbots During the Galway West and Dublin Central Byelections"**](https://www.ucd.ie/connected_politics/blog/auditingaichatbotsduringthegalwaywestanddublincentralbyelections/) **with Eoghan Cunningham, James Cross, Louise Luxton, Timea Balogh, and Derek Greene**
